### ISSUE TITLE
When creating a note, quick settings doesn't automatically collapse

### ISSUE THREAD

**Issue by SimoneG97** [Yanndroid/NotiNotes#8]
Hi,
I'm not really sure if I should consider this an issue since I don't know if it's a wanted behaviour or not, but when I tap on the notinotes quick tile, the quick settings should collapse to show the notinotes new note menu, but it doesn't.
When I tap it, nothing happens at all on screen. Only after manually collapsing the quick settings, I can see the new note menu.
Is this the intended behaviour or is it a bug?

Device: Poco F1
Android version: Android 12

**Comment by Yanndroid** [comment]
Unfortunately, on Android 12+ this is no longer possible / very difficult to archive. [See why](https://developer.android.com/about/versions/12/behavior-changes-all#close-system-dialogs). But I'm working on a fix as we speak and might have found a solution.

**Comment by SimoneG97** [comment]
Wow that was a quick answer!
By the way, that's really weird because there's another app which does a very similar thing that does indeed work.
It is open source too, so you can check how they implemented it if you want!
It's called [p!n](https://github.com/nproth/pin) and I can confirm it can close the quick settings when pressing on the quick tile.

**Comment by Yanndroid** [comment]
Thanks for pointing this out. The difference however is that he probably has an activity and with this you can use `startActivityAndCollapse()`. I'm currently doing a similar thing but I also have the problem with the notification's "Edit" button and for this one there is no such thing.

**Comment by Yanndroid** [comment]
It should now be working in v1.3.5.👌You can download it from the releases or wait until PlayStore updates it (couple hours maybe).
I changed the targetSdkVersion to 30, so that I can use `Intent.ACTION_CLOSE_SYSTEM_DIALOGS` in some cases and I added a Dummy activity for `startActivityAndCollapse()` and unlocking the phone.
I will probably use the activity at some point instead of the overlay but I did this and the 2 previous releases in a rush to get things working again 😅.

**Comment by SimoneG97** [comment]
That was blazingly fast!
And yes, I can confirm that now it closes the quick settings!
